"""create event reports

Revision ID: 696bdbe0b0f5
Revises: a7c8d9e0f1a2
Create Date: 2026-10-08 16:52:21.888268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '696bdbe0b0f5'
down_revision: Union[str, Sequence[str], None] = 'a7c8d9e0f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('spam', 'inappropriate_content', 'harassment', 'other', name='report_reason', native_enum=False, create_constraint=True, length=50), server_default='other', nullable=False),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', 'dismissed', name='report_status', native_enum=False, create_constraint=True, length=20), server_default='open', nullable=False),
    sa.Column('active_event_id', sa.Integer(), sa.Computed("CASE WHEN status = 'open' THEN event_id ELSE NULL END", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolver_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_reports_open_event_per_user', 'events_reports', ['reporter_id', 'active_event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events_reports')
    # ### end Alembic commands ###
