EVENT_TITLE_MAX_LENGTH = 50
EVENT_LOCATION_MAX_LENGTH = 200
EVENT_DESCRIPTION_MAX_LENGTH = 1500
USER_ROLE_MAX_LENGTH = 50
USER_ABOUT_MAX_LENGTH = 1500
REPORT_REASON_MAX_LENGTH = 50
REPORT_DETAILS_MAX_LENGTH = 500
REPORT_STATUS_MAX_LENGTH = 50
