EVENT_TITLE_MAX_LENGTH = 50
EVENT_LOCATION_MAX_LENGTH = 200
EVENT_MIN_PARTICIPANTS = 2
EVENT_MAX_PARTICIPANTS = 100
EVENT_MIN_DURATION_MINUTES = 15
EVENT_MAX_DURATION_MINUTES = 1440
EVENT_DESCRIPTION_MAX_LENGTH = 1500
USER_ABOUT_MAX_LENGTH = 1500
